name: CI-CD
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  eslint:
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js13k-2021
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npx eslint . --fix
  test:
    # ? Attend la fin de eslint pour lancer ce test
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm test

  audit:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm audit

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4      
      - name: Audit Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: './.lighthouserc.js'
          uploadArtifacts: true 