name: CI-CD
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  eslint:
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npx eslint . --fix
      - name: Resume
        run:
          echo "Les fichiers JS respectent les normes."

  test:
    # ? Attend la fin de eslint pour lancer ce test
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm test
      - name: Resume
        run: 
          echo "Résultats des Tests :" >> $GITHUB_STEP_SUMMARY

  audit:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm audit
      - name: Resume
        run: 
          echo:'Listes des dépendances '

  build-docker:
    needs: [test, audit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Images Docker 
        run: docker compose build 